In [13]:
import file_process
import networkx as nx
import matplotlib.pyplot as plt
import env_manager

In [14]:
list_file_graph=['g_27']

In [61]:
em = env_manager.EnvManager(list_file_graph=list_file_graph)

Computing transition probabilities:   0%|          | 0/30 [00:00<?, ?it/s]

In [62]:
env=em.list_env[0]

In [17]:
next_obs, reward, done=env.step(1)

Computing transition probabilities:   0%|          | 0/30 [00:00<?, ?it/s]

In [63]:
obs = env.obs

In [78]:
tensor = obs.T

In [80]:
tensor.shape

torch.Size([1, 30])

In [24]:
from modules import MLP

In [25]:
q_func = MLP(30,30)

In [28]:
q_func.forward(tensor)

DiscreteActionValue greedy_actions:[17] q_values:[[ 0.134734   -0.15081516 -0.07564077  0.07830541 -0.0243895   0.14639059
   0.08749475  0.09740581 -0.15698409 -0.0137997  -0.16769657 -0.10981674
  -0.07042955 -0.06060321 -0.12328409 -0.04983753  0.21039611  0.25099194
   0.00386638  0.15092005  0.01886743 -0.13013977 -0.03549981 -0.03478628
  -0.00788008 -0.10640189 -0.06051455 -0.11519583 -0.18017195  0.09260904]]

In [29]:
from Auto_Encoder import Auto_Encoder

In [31]:
ae = Auto_Encoder(30)

In [36]:
import torch

In [77]:
tensor

tensor([[-0.2251,  1.1957,  0.6450, -0.7688,  0.7911,  0.0343, -0.1131,  0.2159,
          0.6165,  1.0483,  0.7743, -0.0814,  1.1957, -0.0808, -0.6806,  0.3372,
         -0.4022,  0.0555,  0.4615, -0.8343, -0.9438, -0.7306, -1.0454, -0.6094,
          0.9980,  1.0990, -0.5077,  0.0584, -1.1862, -0.5295]])

In [69]:
torch.argmax(tensor).item()

12

In [76]:
tensor[0,1]=tensor[0,12]

In [88]:
tensor1 = torch.rand(1,30)
tensor2 = torch.rand(1,30)

In [89]:
tensor1,tensor2

(tensor([[0.5937, 0.0038, 0.8616, 0.2120, 0.8948, 0.5134, 0.2550, 0.2588, 0.4323,
          0.7329, 0.9744, 0.6170, 0.4268, 0.0971, 0.4553, 0.4788, 0.7462, 0.8045,
          0.6670, 0.1325, 0.9117, 0.9102, 0.2482, 0.7476, 0.8174, 0.0724, 0.3754,
          0.9965, 0.6207, 0.6613]]),
 tensor([[0.5317, 0.6370, 0.1434, 0.3307, 0.5552, 0.6207, 0.1161, 0.8287, 0.6522,
          0.0877, 0.5716, 0.0242, 0.1458, 0.7348, 0.6251, 0.4096, 0.7796, 0.7968,
          0.5252, 0.9756, 0.5524, 0.4655, 0.7715, 0.8274, 0.3210, 0.8642, 0.6489,
          0.2909, 0.5091, 0.5664]]))

In [107]:
t=torch.cat((tensor1,tensor2),0)

In [108]:
t.shape

torch.Size([2, 30])

In [105]:
Y = torch.ones(2, 2, 2)
print(Y)
print(Y.shape)
y3= torch.zeros(2, 2, 2)
y4 = torch.cat((Y,y3),1)  # 在第一维上进行cat拼接
print(y4)
print(y4.shape)

tensor([[[1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.]]])
torch.Size([2, 2, 2])
tensor([[[1., 1.],
         [1., 1.],
         [0., 0.],
         [0., 0.]],

        [[1., 1.],
         [1., 1.],
         [0., 0.],
         [0., 0.]]])
torch.Size([2, 4, 2])


In [109]:
import csv

In [ ]:
fileHeader = ["name", "score"]

# 假设我们要写入的是以下两行数据
d1 = ["Wang", "100"]
d2 = ["Li", "80"]

# 写入数据

csvFile = open("instance.csv", "w")
writer = csv.writer(csvFile)

# 写入的内容都是以列表的形式传入函数
writer.writerow(fileHeader)
writer.writerow(d1)
writer.writerow(d1)

csvFile.close()

In [110]:
fileHeader = ["name", "score"]

# 假设我们要写入的是以下两行数据
d1 = ["Wang", "100"]
d2 = ["Li", "80"]

In [116]:
with open("instance.csv", "w",encoding='utf8', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(fileHeader)
    writer.writerow(d1)
    f.close()

In [113]:
writer.writerow(d1)

ValueError: I/O operation on closed file.

In [118]:
fileHeader = ["Episode", "step", 'reward', 'total_reward']
with open("result.csv", "a", encoding='utf8', newline='') as f:
    writer = csv.writer(f)
    writer.writerow(fileHeader)
    f.close()

In [1]:
import torch

In [2]:
torch.cuda.is_available()

True